#!/bin/sh
# Converts a word list (default: /usr/share/dict/linux.words) into words.h,
# keeping only 5-letter all-lowercase words (drops proper nouns/abbreviations).
# Usage: sh gen_words.sh [wordlist] > words.h
IN="${1:-/usr/share/dict/linux.words}"
if [ ! -r "$IN" ]; then
    echo "gen_words.sh: cannot read $IN (install the 'words' package, or pass a path)" >&2
    exit 1
fi

echo "// Generated by gen_words.sh from $(basename "$IN") -- do not edit."
echo "#ifndef WORDS_H"
echo "#define WORDS_H"
echo "#include <stddef.h>"
echo ""
echo "static const char* const VALID_WORDS[] = {"
tr -d '\r' < "$IN" | grep -E '^[a-z]{5}$' | LC_ALL=C sort -u |
    awk '{ printf "%s\"%s\",", (NR % 12 == 1 ? "    " : " "), $0; if (NR % 12 == 0) printf "\n" }
         END { if (NR % 12 != 0) printf "\n" }'
echo "};"
echo ""
echo "static const size_t VALID_WORDS_COUNT = sizeof(VALID_WORDS) / sizeof(VALID_WORDS[0]);"
echo ""
echo "#endif // WORDS_H"
