#!/bin/sh
# Converts a word list (default: /usr/share/dict/linux.words) into words.h:
# every 4- to 7-letter all-lowercase word (drops proper nouns/abbreviations),
# one sorted array per length, packed n letters apiece with no separators so
# 90,000 words cost no pointers and can be binary-searched in place.
# Usage: sh gen_words.sh [wordlist] > words.h
IN="${1:-/usr/share/dict/linux.words}"
if [ ! -r "$IN" ]; then
    echo "gen_words.sh: cannot read $IN (install the 'words' package, or pass a path)" >&2
    exit 1
fi

echo "// Generated by gen_words.sh from $(basename "$IN") -- do not edit."
echo "#ifndef WORDS_H"
echo "#define WORDS_H"
echo "#include <stddef.h>"
for n in 4 5 6 7; do
    echo ""
    echo "// All ${n}-letter words, sorted (C locale), ${n} letters each."
    echo "static const char VALID_WORDS_${n}[] ="
    tr -d '\r' < "$IN" | grep -E "^[a-z]{${n}}\$" | LC_ALL=C sort -u |
        awk -v per=$((60 / n)) '{ line = line $0; if (NR % per == 0) { printf "    \"%s\"\n", line; line = "" } }
                                END { if (line != "") printf "    \"%s\"\n", line; if (NR == 0) printf "    \"\"\n" }'
    echo "    ;"
    echo "static const size_t VALID_WORDS_${n}_COUNT = (sizeof(VALID_WORDS_${n}) - 1) / ${n};"
done
echo ""
echo "#endif // WORDS_H"
