#!/usr/bin/env python3
"""Rasterize the game's embedded DejaVu Sans Mono (../DejaVuMono.h) at every
point size letterlock.cpp asks SDL_ttf for, as anti-aliased bitmaps, so the
bare-metal build draws the same text without FreeType.

    python3 tools/gen_fonts.py ../DejaVuMono.h > fonts.h        (needs Pillow)

SDL_ttf renders at 72 dpi, so a point size is a pixel size here too.

To keep the kernel small enough for a boot floppy, coverage is stored at 16
levels (one 0-15 value per byte, which compresses well), and only the
characters the game can draw are baked: capitals, digits and a little
punctuation at every size, plus lowercase at the 15 pt size used for the
"Letterlock (muted)" title. Anything else draws as '?'.
"""
import base64, io, re, sys
from PIL import Image, ImageDraw, ImageFont

SIZES = [11, 13, 14, 15, 16, 18, 20, 30, 34, 36]   # every size letterlock.cpp uses
BASIC = " %()+,-./0123456789:?!'ABCDEFGHIJKLMNOPQRSTUVWXYZ"
FULL = {15}                                        # sizes that get all of ASCII 32..126

src = open(sys.argv[1]).read()
blob = src.split("DEJAVU_REGULAR_FONT_B64[] =", 1)[1].split(";", 1)[0]
ttf = base64.b64decode("".join(re.findall(r'"([A-Za-z0-9+/=]*)"', blob)))

out = sys.stdout
out.write("// Generated by tools/gen_fonts.py from DejaVu Sans Mono (../DejaVuMono.h). Do not edit.\n")
out.write("// Coverage 0-15 per pixel, one cell per glyph, baseline at `ascent`. `index` maps\n")
out.write("// ASCII 32..126 to a glyph in `cov`, or -1 when that character wasn't baked.\n")
out.write("#pragma once\n#include <stdint.h>\n\n")
out.write("struct BakedFont { int pt, adv, height, ascent, cap_h; const int8_t* index; const uint8_t* cov; };\n\n")
table = []
for pt in SIZES:
    font = ImageFont.truetype(io.BytesIO(ttf), pt)
    ascent, descent = font.getmetrics()
    adv = round(font.getlength("M"))
    height = ascent + descent
    cap_h = -font.getbbox("H", anchor="ls")[1]
    chars = [chr(c) for c in range(32, 127)] if pt in FULL else sorted(set(BASIC))
    index = [-1] * 95
    for i, ch in enumerate(chars):
        index[ord(ch) - 32] = i
    out.write(f"static const int8_t font_index_{pt}[95] = {{{','.join(map(str, index))}}};\n")
    out.write(f"static const uint8_t font_cov_{pt}[{len(chars)} * {height} * {adv}] = {{\n")
    for ch in chars:
        img = Image.new("L", (adv, height), 0)
        ImageDraw.Draw(img).text((0, ascent), ch, font=font, fill=255, anchor="ls")
        px = img.tobytes()
        out.write("  " + ",".join(str((v * 15 + 127) // 255) for v in px) + ",\n")
    out.write("};\n")
    table.append(f"    {{{pt}, {adv}, {height}, {ascent}, {cap_h}, font_index_{pt}, font_cov_{pt}}},\n")
out.write("\nstatic const BakedFont baked_fonts[] = {\n" + "".join(table) + "};\n")
