#!/usr/bin/env python3
"""Rasterize the game's embedded DejaVu Sans Mono (../DejaVuMono.h) at every
point size wordle.cpp asks SDL_ttf for, as anti-aliased bitmaps, so the
bare-metal build draws the same text without FreeType.

    python3 tools/gen_fonts.py ../DejaVuMono.h > fonts.h        (needs Pillow)

SDL_ttf renders at 72 dpi, so a point size is a pixel size here too.
"""
import base64, io, re, sys
from PIL import Image, ImageDraw, ImageFont

SIZES = [11, 13, 14, 15, 16, 18, 20, 30, 34, 36]   # every size wordle.cpp uses

src = open(sys.argv[1]).read()
blob = src.split("DEJAVU_REGULAR_FONT_B64[] =", 1)[1].split(";", 1)[0]
ttf = base64.b64decode("".join(re.findall(r'"([A-Za-z0-9+/=]*)"', blob)))

out = sys.stdout
out.write("// Generated by tools/gen_fonts.py from DejaVu Sans Mono (../DejaVuMono.h). Do not edit.\n")
out.write("// 8-bit coverage, one cell per glyph (ASCII 32..126), baseline at `ascent`.\n")
out.write("#pragma once\n#include <stdint.h>\n\n")
out.write("struct BakedFont { int pt, adv, height, ascent, cap_h; const uint8_t* cov; };\n\n")
for pt in SIZES:
    font = ImageFont.truetype(io.BytesIO(ttf), pt)
    ascent, descent = font.getmetrics()
    adv = round(font.getlength("M"))
    height = ascent + descent
    cap_h = -font.getbbox("H", anchor="ls")[1]
    out.write(f"static const uint8_t font_cov_{pt}[95 * {height} * {adv}] = {{\n")
    for c in range(32, 127):
        img = Image.new("L", (adv, height), 0)
        ImageDraw.Draw(img).text((0, ascent), chr(c), font=font, fill=255, anchor="ls")
        out.write("  " + ",".join(str(v) for v in img.getdata()) + ",\n")
    out.write("};\n")
out.write("\nstatic const BakedFont baked_fonts[] = {\n")
for pt in SIZES:
    font = ImageFont.truetype(io.BytesIO(ttf), pt)
    ascent, descent = font.getmetrics()
    adv = round(font.getlength("M"))
    cap_h = -font.getbbox("H", anchor="ls")[1]
    out.write(f"    {{{pt}, {adv}, {ascent + descent}, {ascent}, {cap_h}, font_cov_{pt}}},\n")
out.write("};\n")
